name: functional_listener
description: An rx like extension methods on ValueListenable type, that lets you work with ValueNotifiers almost like with Streams
version: 2.0.0
author: Thomas Burkhart
homepage: https://github.com/escamoteur/functional_listener

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter
